name: demo
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dependencies:
  http: ^0.13.3

dev_dependencies:
  build_runner: ">=1.6.2 <3.0.0"
  linter: ^1.30.0
  lints: ^2.0.0
  build_web_compilers: ^4.0.0