apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: username
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-init
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-init
          configMap:
            name: mariadb-init-script