apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: gitlab-registry-{{ CI_PROJECT_ID }}
      containers:
      - name: backend-container
        image: {{ CI_REGISTRY_IMAGE }}/backend:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 30